// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyProjectAPI.Models;

namespace PropertyProjectAPI.Migrations
{
    [DbContext(typeof(PropertyDetailContext))]
    [Migration("20210428044801_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PropertyProjectAPI.Models.PropertyDetail", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("County")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("GrossYield")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("DECIMAL(19,4)");

                    b.Property<decimal>("MonthlyRent")
                        .HasColumnType("DECIMAL(19,4)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<string>("Zip")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("ZipPlus4")
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
